site_name: Polars-ds API References
site_url: https://polars-ds-extension.readthedocs.io/en/latest/

use_directory_urls: false

nav:
- Home: index.md
- Diagnosis: dia.md
- Pipeline: pipeline.md
- Sample: sample.md
- Linear Models: linear_models.md
- Time Series Features: features.md
- KNN Queries: query_knn.md
- Lstsq Queries: query_linear.md
- Numerical Functions: num.md
- Statistics: stats.md
- String Related: string.md
- ML Metrics/Loss: metrics.md
- Miscellaneous: polars_ds.md

theme:
  name: material
  locale: en
  highlightjs: true

plugins:
- search
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [python]
        options:
          summary: true
          docstring_style: numpy